---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Builder
    package:
      name: gnome-builder
      state: present

  - name: Install Spotify
    become: yes
    command: flatpak install --assumeyes flathub com.spotify.Client
