%YAML 1.3
---
- Rule:
  - Key: [Open Emoji Panel, pressed]
  - Execute: gnome-characters
...
---
- Key: [Mouse Gesture Button, pressed]
- KeyPress:
  - Super_L
  - click
...
---
- Key: [Snipping Tool, pressed]
- KeyPress:
  - Print
  - click
...