# Created by newuser for 5.9

eval "$(starship init zsh)"

#zsh auto suggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

#bindings
bindkey '^[[1;5C' forward-word     # Ctrl+right arrow
bindkey '^[[1;5D' backward-word    # Ctrl+left arrow
bindkey "^[[3~" delete-char        # Del button to delete front